server:
  port: 14100
  compression:
    enabled: true
    mime-types: 'text/html,text/xml,text/css,text/javascript,text/plain'
  tomcat:
    max-connections: 500
    max-threads: 100
spring:
  profiles:
    active: local    #\u9ED8\u8BA4\u6FC0\u6D3Blocal\u914D\u7F6E
  boot:
    admin:
      client:
        prefer-ip: true
---
spring:
  profiles: local
eureka:
  server:
    enable-self-preservation: false               # \u5173\u95ED\u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F\uFF08\u7F3A\u7701\u4E3A\u6253\u5F00\uFF09
    eviction-interval-timer-in-ms: 5000           # \u7EED\u671F\u65F6\u95F4\uFF0C\u5373\u626B\u63CF\u5931\u6548\u670D\u52A1\u7684\u95F4\u9694\u65F6\u95F4\uFF08\u7F3A\u7701\u4E3A60*1000ms\uFF09
  client:
    registerWithEureka: false                     #\u662F\u5426\u5C06eureka\u81EA\u8EAB\u4F5C\u4E3A\u5E94\u7528\u6CE8\u518C\u5230eureka\u6CE8\u518C\u4E2D\u5FC3
    fetchRegistry: false                          #\u4E3Atrue\u65F6\uFF0C\u53EF\u4EE5\u542F\u52A8\uFF0C\u4F46\u62A5\u5F02\u5E38\uFF1ACannot execute request on any known server
logging:
  level:
    root: INFO